apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    apptype: web-backend  # Ensure this matches Service selector
spec:
  replicas: 4
  selector:
    matchLabels:
      apptype: web-backend  # Ensure this matches Service selector
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        apptype: web-backend  # Ensure this matches Service selector
    spec:
      containers:
      - name: my-app
        image: ashilin20/app:latest
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    apptype: web-backend  # Make labels consistent
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 5050
      nodePort: 30001
